import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
import 'vue-awesome/icons/apple'
import 'vue-awesome/icons/arrow-left'
import 'vue-awesome/icons/arrow-right'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/chevron-right'
import 'vue-awesome/icons/github'
import 'vue-awesome/icons/medium'
import 'vue-awesome/icons/pause'
import 'vue-awesome/icons/pencil-square-o'
import 'vue-awesome/icons/play'
import 'vue-awesome/icons/rotate-right'
import 'vue-awesome/icons/rss'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/spinner'
import 'vue-awesome/icons/tachometer'
import 'vue-awesome/icons/times'
import 'vue-awesome/icons/twitter'
import 'vue-awesome/icons/volume-off'
import 'vue-awesome/icons/volume-up'

Vue.component('icon', Icon)
