import Vue from 'vue'
import Icon from 'vue-awesome/components/Icon.vue'
import 'vue-awesome/icons/brands/apple'
import 'vue-awesome/icons/brands/github'
import 'vue-awesome/icons/brands/medium'
import 'vue-awesome/icons/brands/twitter'
import 'vue-awesome/icons/arrow-left'
import 'vue-awesome/icons/arrow-right'
import 'vue-awesome/icons/bars'
import 'vue-awesome/icons/chevron-right'
import 'vue-awesome/icons/pause'
import 'vue-awesome/icons/edit'
import 'vue-awesome/icons/play'
import 'vue-awesome/icons/undo'
import 'vue-awesome/icons/redo'
import 'vue-awesome/icons/rss'
import 'vue-awesome/icons/search'
import 'vue-awesome/icons/spinner'
import 'vue-awesome/icons/tachometer-alt'
import 'vue-awesome/icons/times'
import 'vue-awesome/icons/volume-off'
import 'vue-awesome/icons/volume-up'
import 'vue-awesome/icons/external-link-alt'

Vue.component('v-icon', Icon)
